#![no_main]

extern crate libc;

trait ResultExt <T> {
    fn unwr(self) -> T;
}

impl<T> ResultExt<T> for Result<T, String>{
    fn unwr(self) -> T{
        match self {
            Ok(v) => v,
            Err(e) => {
                unsafe {
                    libc::printf(e.as_bytes().as_ptr() as *const i8);
                    
                }
                std::process::exit(1);
            }
        }
    }
}



#[no_mangle]
pub extern fn run() {
    let src = std::fs::read_to_string("examples/1.asm").unwrap();
    /*let src = match std::fs::read_to_string("examples/12.asm") {
        Ok(v) => v,
        Err(e) => {
            
            std::process::exit(1);
        }
    };*/
    //std::io::stdout().write(src.as_bytes());
    //let s = "eoauHeOEUOOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoaueoaueoauoauaoueaoueoauevvHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEeoauHeOEUOOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoaueoaueoauoauaoueaoueoauevvHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOEUEOUEOUoeuauaoeueoauaouaeoauoauoaueoaueoauoauaoueaoueoauHeOEUOEUOEUOEUOEUOEUOEUOUOEUOEUOEUOEUOEUO";
    unsafe {
        libc::printf(src.as_bytes().as_ptr() as *const i8);
        
    }
    
    //ncvm_asm::compile_asm(src).unwr();
    //crate::compile_asm(".in(\n00\n)".to_string()).unwrap();
    //crate::compile_asm(".in(\n00\n)".to_string()).unwrap();
    let a = ncvm_asm::compile_asm("src".to_string()).unwr();
}